### ISSUE TITLE
Hotbars Greyed Out

### ISSUE THREAD

**Issue by GM-Odran** [IronWillGames/AshenEmpires#17]
There has been a previous fix for this however the CTRL, ALT and SHIFT sections of the hotbar grey out on log in / out. When you log in, any items on the CTRL, ALT or SHIFT side of the hotbars are greyed out (even when they are in your backpack)

**Comment by curxxx** [comment]
This happens with random items (mostly runes) on the hotbars without modifiers too

**Comment by TheMageMerlin** [comment]
sometimes it gets fixed by opening and closing containers. Most of the time I have to press and hold shift and drag the rune off to the side and drop it, and that makes it available again

**Comment by davidjreese** [comment]
I think I fixed this. I couldn't repro though so just found something suspicious in a code read that I updated. let me know if it is still happending after the next patch (reopen this)

**Comment by GM-Odran** [comment]
Still broken

**Comment by TheMageMerlin** [comment]
![hotbar](https://user-images.githubusercontent.com/113220709/191877362-c5248127-7dbe-444e-b090-68019ad2e6f3.PNG)

confirmed. still broken

**Comment by Whitegrave** [comment]
Yes, not resolved yet 
![image](https://user-images.githubusercontent.com/29662888/192118713-7ca18ed5-6541-472b-92dc-8ada8cbe0fab.png)

**Comment by davidjreese** [comment]
Found this and fixed it finally. It will go out with the next release

**Comment by hgesler** [comment]
Can anyone confirm this is fixed? @Whitegrave @GM-Odran @TheMageMerlin @curxxx ?

**Comment by GM-Odran** [comment]
> Can anyone confirm this is fixed? @Whitegrave @GM-Odran @TheMageMerlin @curxxx ?

@hgesler confirming fixed.

**Comment by TheMageMerlin** [comment]
> 

I will confirm fixed as well. Haven't had it happen anymore

**Comment by hgesler** [comment]
Hallelujah 🖐️
